export const SN_PROMOTION_PLATFORM = 'promotionPlatform';
export const SET_CAMPAIGN_CONTENT = SN_PROMOTION_PLATFORM + '/SET_CAMPAIGN_CONTENT';
export const SET_CAMPAIGN_TOKEN = SN_PROMOTION_PLATFORM + '/SET_CAMPAIGN_TOKEN';
