export const SN_PROMOTION_PLATFORM = 'promotionPlatform';
export const SET_CAMPAIGN_CONTENT = SN_PROMOTION_PLATFORM + '/SET_CAMPAIGN_CONTENT';
export const SET_CAMPAIGN_TOKEN = SN_PROMOTION_PLATFORM + '/SET_CAMPAIGN_TOKEN';
export const SET_LAST_BANNER_VERSION_CLOSED_BY_USER = SN_PROMOTION_PLATFORM + '/SET_LAST_BANNER_VERSION_CLOSED_BY_USER';
