export const SN_PROMOTION_PLATFORM = 'promotionPlatform';
export const SET_CAMPAIGN_CONTENT = SN_PROMOTION_PLATFORM + '/SET_CAMPAIGN_CONTENT';
export const SET_CAMPAIGN_TOKEN = SN_PROMOTION_PLATFORM + '/SET_CAMPAIGN_TOKEN';
export const SET_IS_SYNCED = SN_PROMOTION_PLATFORM + '/SET_IS_SYNCED';
export const SET_LAST_BANNER_VERSION_CLOSED_BY_USER = SN_PROMOTION_PLATFORM + '/SET_LAST_BANNER_VERSION_CLOSED_BY_USER';
export const SET_PRODUCTION_SPOT_COUNTDOWN_EXPIRATION_DATE = SN_PROMOTION_PLATFORM + '/SET_PRODUCTION_SPOT_COUNTDOWN_EXPIRATION_DATE';
export const CLEAR_PRODUCTION_SPOT_COUNTDOWN_EXPIRATION_DATE = SN_PROMOTION_PLATFORM + '/CLEAR_PRODUCTION_SPOT_COUNTDOWN_EXPIRATION_DATE';
