ci:
- .github/**/*

cache:
- packages/cache/**/*

cli:
- packages/cli/**/*

core:
- packages/core/**/*

docs:
- packages/docs/**/*
- packages/docs/.vuepress/**/*

health-check:
- packages/health-check/**/*

middleware:
- packages/middleware/**/*

nuxt-module:
- packages/nuxt-module/**/*

nuxt-theme-module:
- packages/nuxt-theme-module/**/*
