# Add 'Next' label to any change to packages files
Next:
- true

# Add 'core' label to any change to packages/core files within the source dir EXCEPT for the docs sub-folder
core:
- any: ['packages/**/*', '!packages/docs/**/*']

# Add 'boilerplate' label to any change to packages/boilerplate files
boilerplate:
- packages/boilerplate/**/*

# Add 'docs' label to any change to packages/docs files
docs:
- packages/docs/**/*
- packages/docs/.vuepress/**/*

# Add 'ci' label to any change to continuous integration files inside .github folder
ci:
- .github/**/*
