titleOnly: true
scopes:
  - ci
  - cache
  - cli
  - core
  - docs
  - health-check
  - middleware
  - nuxt-module
  - nuxt-theme-module
types:
  - feat
  - fix
  - improvement
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - rfc
