export const SN_CATEGORY = 'category'
export const CATEGORY_SET_PRODUCTS = `${SN_CATEGORY}/SET_PRODUCTS`
export const CATEGORY_SET_CATEGORIES = `${SN_CATEGORY}/SET_CATEGORIES`
export const CATEGORY_SET_AVAILABLE_FILTERS = `${SN_CATEGORY}/SET_AVAILABLE_FILTERS`
