approvedGitRepositories:
  - "**"

enableGlobalCache: true

enableScripts: true

nmHoistingLimits: none

packageExtensions:
  "quicklink@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true

nodeLinker: node-modules

npmMinimalAgeGate: 0
