cacheFolder: ./.yarn/cache

defaultLanguageName: node

defaultProtocol: "npm:"

enableColors: true

enableGlobalCache: false

enableHyperlinks: true

enableInlineBuilds: true

enableProgressBars: true

logFilters:
  - code: YN0000
    level: info
  - code: YN0001
    level: info
  - code: YN0007
    level: info
  - code: YN0009
    level: info
  - code: YN0010
    level: info
  - code: YN0011
    level: info
  - code: YN0013
    level: info
  - code: YN0014
    level: info
  - code: YN0015
    level: info
  - code: YN0016
    level: info
  - code: YN0032
    level: info
  - code: YN0059
    level: info
  - code: YN0060
    level: info
  - code: YN0061
    level: info


nmHoistingLimits: workspaces

nodeLinker: node-modules

npmAlwaysAuth: true

npmPublishAccess: restricted

npmPublishRegistry: "https://registry.npmjs.org"

pnpFallbackMode: all

pnpMode: strict

preferInteractive: true

yarnPath: .yarn/releases/yarn-2.4.2.cjs
