#!/bin/sh

docker exec storefront pm2 restart 0

echo " === VSF -> storefront Restarted \n"
echo "docker storefront logs       ->   (VSF Vue)"
echo "docker storefront_api logs    ->   (VSF API)"
echo "docker procc logs            ->   (ProCC Vue)"
echo "docker procc logs            ->   (ProCC API)"


