#!/bin/sh

docker-compose -f docker-compose-dev.yml up -d

echo " === VSF -> storefront Restarted \n"
echo "docker storefront logs       ->   (VSF Vue)"
echo "docker storefront_api logs    ->   (VSF API)"
echo "docker procc logs            ->   (ProCC Vue)"
echo "docker procc logs            ->   (ProCC API)"

sh logs

/bin/sh
exec "$@"
