const ignoredQueryKeys = [
  'srsltid',
  'utm_source',
  'utm_medium',
  'utm_campaign',
  '_kx',
  'fbclid',
  'utm_term',
  'utm_content',
  'utm_id',
  'gad_source',
  'gclid',
  'id',
  'gbraid',
  'dclid',
  'campaign',
  'data',
  'content',
  'msclkid',
  'uri',
  'url',
  'dest',
  'redirect',
  'file',
  'target',
  'mc_cid',
  'mc_eid',
  'sscid',
  'gad_campaignid',
  'gQT',
  'wbraid',
  'ttclid',
  'li_fat_id',
  'twclid',
  'sccid',
  'rdt_cid',
  'irclickid',
  'awc',
  'pp',
  'audience',
  'ref',
  'continueFlag',
  'hc_location',
  'qty',
  'email',
  'epik',
  'user',
  'SID',
  'referral_code',
  'newsletter-subscription-form-email-input',
  'redirect-target',
  'coupon_code',
  'applyPromoCode',
  'image-url',
  'order_item_id'
];

export function generatePageCacheKey (site: string, requestUrl: string): string {
  const url = new URL(requestUrl);

  ignoredQueryKeys.forEach((key) => url.searchParams.delete(key));

  return `page:${site}:${url.pathname}${url.search}`;
}
