export const rawConfigurableProductAttributesMetadata = () => [
  {
    'is_visible_on_front': '0',
    'is_visible': true,
    'default_frontend_label': 'Color',
    'attribute_id': 93,
    'entity_type_id': '4',
    'id': 93,
    'frontend_input': 'select',
    'is_user_defined': true,
    'is_comparable': '0',
    'attribute_code': 'color',
    'options': [
      {
        'label': 'Black',
        'value': '49'
      },
      {
        'label': 'Blue',
        'value': '50'
      },
      {
        'label': 'Green',
        'value': '53'
      }
    ]
  },
  {
    'is_visible_on_front': '0',
    'is_visible': true,
    'default_frontend_label': 'Size',
    'attribute_id': 142,
    'entity_type_id': '4',
    'id': 142,
    'frontend_input': 'select',
    'is_user_defined': true,
    'is_comparable': '0',
    'attribute_code': 'size',
    'options': [
      {
        'label': 'XS',
        'value': '167'
      },
      {
        'label': 'S',
        'value': '168'
      },
      {
        'label': 'M',
        'value': '169'
      },
      {
        'label': 'L',
        'value': '170'
      },
      {
        'label': 'XL',
        'value': '171'
      }
    ]
  }
]

export const rawConfigurableProduct = () => ({
  'id': 99,
  'sku': 'MH03',
  'name': 'Bruno Compete Hoodie',
  'price': 63,
  'status': 1,
  'visibility': 4,
  'type_id': 'configurable',
  'product_links': [],
  'custom_attributes': null,
  'final_price': 63,
  'max_price': 63,
  'max_regular_price': 63,
  'minimal_regular_price': 63,
  'special_price': null,
  'minimal_price': 63,
  'regular_price': 63,
  'description': "<p>Stay comfortable and stay in the race no matter what the weather's up to. The Bruno Compete Hoodie's water-repellent exterior shields you from the elements, while advanced fabric technology inside wicks moisture to keep you dry.</p> <p>&bull; Full zip black hoodie pullover. <br />&bull; Adjustable drawstring hood. <br />&bull; Ribbed cuffs/waistband. <br />&bull; Kangaroo pocket. <br />&bull; Machine wash/dry.</p>",
  'image': '/m/h/mh03-black_main.jpg',
  'small_image': '/m/h/mh03-black_main.jpg',
  'thumbnail': '/m/h/mh03-black_main.jpg',
  'category_ids': [ 15, 36, 2 ],
  'required_options': '0',
  'has_options': '1',
  'url_key': 'bruno-compete-hoodie',
  'tax_class_id': '2',
  'material': '154',
  'new': '1',
  'sale': '0',
  'pattern': '197',
  'slug': 'bruno-compete-hoodie-99',
  'stock': {
    'item_id': 99,
    'product_id': 99,
    'stock_id': 1,
    'qty': 0,
    'is_in_stock': true,
    'is_qty_decimal': false,
    'show_default_notification_message': false,
    'use_config_min_qty': true,
    'min_qty': 0,
    'use_config_min_sale_qty': 1,
    'min_sale_qty': 1,
    'use_config_max_sale_qty': true,
    'max_sale_qty': 10000,
    'use_config_backorders': true,
    'backorders': 0,
    'use_config_notify_stock_qty': true,
    'notify_stock_qty': 1,
    'use_config_qty_increments': true,
    'qty_increments': 0,
    'use_config_enable_qty_inc': true,
    'enable_qty_increments': false,
    'use_config_manage_stock': true,
    'manage_stock': true,
    'low_stock_date': null,
    'is_decimal_divided': false,
    'stock_status_changed_auto': 0
  },
  'media_gallery': [
    {
      'image': '/m/h/mh03-black_main.jpg',
      'pos': 1,
      'typ': 'image',
      'lab': '',
      'vid': null
    },
    {
      'image': '/m/h/mh03-black_alt1.jpg',
      'pos': 2,
      'typ': 'image',
      'lab': '',
      'vid': null
    },
    {
      'image': '/m/h/mh03-black_back.jpg',
      'pos': 3,
      'typ': 'image',
      'lab': '',
      'vid': null
    }
  ],
  'configurable_children': [
    {
      'sku': 'MH03-XS-Black',
      'id': 84,
      'status': 1,
      'name': 'Bruno Compete Hoodie-XS-Black',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '167',
      'color': '49',
      'image': '/m/h/mh03-black_main.jpg',
      'small_image': '/m/h/mh03-black_main.jpg',
      'thumbnail': '/m/h/mh03-black_main.jpg',
      'url_key': 'bruno-compete-hoodie-xs-black',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-XS-Blue',
      'id': 85,
      'status': 1,
      'name': 'Bruno Compete Hoodie-XS-Blue',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '167',
      'color': '50',
      'image': '/m/h/mh03-blue_main.jpg',
      'small_image': '/m/h/mh03-blue_main.jpg',
      'thumbnail': '/m/h/mh03-blue_main.jpg',
      'url_key': 'bruno-compete-hoodie-xs-blue',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-XS-Green',
      'id': 86,
      'status': 1,
      'name': 'Bruno Compete Hoodie-XS-Green',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '167',
      'color': '53',
      'image': '/m/h/mh03-green_main.jpg',
      'small_image': '/m/h/mh03-green_main.jpg',
      'thumbnail': '/m/h/mh03-green_main.jpg',
      'url_key': 'bruno-compete-hoodie-xs-green',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-S-Black',
      'id': 87,
      'status': 1,
      'name': 'Bruno Compete Hoodie-S-Black',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '168',
      'color': '49',
      'image': '/m/h/mh03-black_main.jpg',
      'small_image': '/m/h/mh03-black_main.jpg',
      'thumbnail': '/m/h/mh03-black_main.jpg',
      'url_key': 'bruno-compete-hoodie-s-black',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-S-Blue',
      'id': 88,
      'status': 1,
      'name': 'Bruno Compete Hoodie-S-Blue',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '168',
      'color': '50',
      'image': '/m/h/mh03-blue_main.jpg',
      'small_image': '/m/h/mh03-blue_main.jpg',
      'thumbnail': '/m/h/mh03-blue_main.jpg',
      'url_key': 'bruno-compete-hoodie-s-blue',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-S-Green',
      'id': 89,
      'status': 1,
      'name': 'Bruno Compete Hoodie-S-Green',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '168',
      'color': '53',
      'image': '/m/h/mh03-green_main.jpg',
      'small_image': '/m/h/mh03-green_main.jpg',
      'thumbnail': '/m/h/mh03-green_main.jpg',
      'url_key': 'bruno-compete-hoodie-s-green',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-M-Black',
      'id': 90,
      'status': 1,
      'name': 'Bruno Compete Hoodie-M-Black',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '169',
      'color': '49',
      'image': '/m/h/mh03-black_main.jpg',
      'small_image': '/m/h/mh03-black_main.jpg',
      'thumbnail': '/m/h/mh03-black_main.jpg',
      'url_key': 'bruno-compete-hoodie-m-black',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-M-Blue',
      'id': 91,
      'status': 1,
      'name': 'Bruno Compete Hoodie-M-Blue',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '169',
      'color': '50',
      'image': '/m/h/mh03-blue_main.jpg',
      'small_image': '/m/h/mh03-blue_main.jpg',
      'thumbnail': '/m/h/mh03-blue_main.jpg',
      'url_key': 'bruno-compete-hoodie-m-blue',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-M-Green',
      'id': 92,
      'status': 1,
      'name': 'Bruno Compete Hoodie-M-Green',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '169',
      'color': '53',
      'image': '/m/h/mh03-green_main.jpg',
      'small_image': '/m/h/mh03-green_main.jpg',
      'thumbnail': '/m/h/mh03-green_main.jpg',
      'url_key': 'bruno-compete-hoodie-m-green',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-L-Black',
      'id': 93,
      'status': 1,
      'name': 'Bruno Compete Hoodie-L-Black',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '170',
      'color': '49',
      'image': '/m/h/mh03-black_main.jpg',
      'small_image': '/m/h/mh03-black_main.jpg',
      'thumbnail': '/m/h/mh03-black_main.jpg',
      'url_key': 'bruno-compete-hoodie-l-black',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-L-Blue',
      'id': 94,
      'status': 1,
      'name': 'Bruno Compete Hoodie-L-Blue',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '170',
      'color': '50',
      'image': '/m/h/mh03-blue_main.jpg',
      'small_image': '/m/h/mh03-blue_main.jpg',
      'thumbnail': '/m/h/mh03-blue_main.jpg',
      'url_key': 'bruno-compete-hoodie-l-blue',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-L-Green',
      'id': 95,
      'status': 1,
      'name': 'Bruno Compete Hoodie-L-Green',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '170',
      'color': '53',
      'image': '/m/h/mh03-green_main.jpg',
      'small_image': '/m/h/mh03-green_main.jpg',
      'thumbnail': '/m/h/mh03-green_main.jpg',
      'url_key': 'bruno-compete-hoodie-l-green',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-XL-Black',
      'id': 96,
      'status': 1,
      'name': 'Bruno Compete Hoodie-XL-Black',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '171',
      'color': '49',
      'image': '/m/h/mh03-black_main.jpg',
      'small_image': '/m/h/mh03-black_main.jpg',
      'thumbnail': '/m/h/mh03-black_main.jpg',
      'url_key': 'bruno-compete-hoodie-xl-black',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-XL-Blue',
      'id': 97,
      'status': 1,
      'name': 'Bruno Compete Hoodie-XL-Blue',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '171',
      'color': '50',
      'image': '/m/h/mh03-blue_main.jpg',
      'small_image': '/m/h/mh03-blue_main.jpg',
      'thumbnail': '/m/h/mh03-blue_main.jpg',
      'url_key': 'bruno-compete-hoodie-xl-blue',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    },
    {
      'sku': 'MH03-XL-Green',
      'id': 98,
      'status': 1,
      'name': 'Bruno Compete Hoodie-XL-Green',
      'price': 63,
      'tier_prices': [],
      'required_options': '0',
      'has_options': '0',
      'tax_class_id': '2',
      'category_ids': ['15', '36', '2'],
      'size': '171',
      'color': '53',
      'image': '/m/h/mh03-green_main.jpg',
      'small_image': '/m/h/mh03-green_main.jpg',
      'thumbnail': '/m/h/mh03-green_main.jpg',
      'url_key': 'bruno-compete-hoodie-xl-green',
      'msrp_display_actual_price_type': '0',
      'final_price': 63,
      'max_price': 63,
      'max_regular_price': 63,
      'minimal_regular_price': 63,
      'special_price': null,
      'minimal_price': 63,
      'regular_price': 63
    }
  ],
  'configurable_options': [
    {
      'id': 7,
      'attribute_id': '93',
      'label': 'Color',
      'position': 1,
      'values': [
        {
          'value_index': 49,
          'label': 'Black'
        },
        {
          'value_index': 50,
          'label': 'Blue'
        },
        {
          'value_index': 53,
          'label': 'Green'
        }
      ],
      'product_id': 99,
      'attribute_code': 'color'
    },
    {
      'id': 6,
      'attribute_id': '142',
      'label': 'Size',
      'position': 0,
      'values': [
        {
          'value_index': 167,
          'label': 'XS'
        },
        {
          'value_index': 168,
          'label': 'S'
        },
        {
          'value_index': 169,
          'label': 'M'
        },
        {
          'value_index': 170,
          'label': 'L'
        },
        {
          'value_index': 171,
          'label': 'XL'
        }
      ],
      'product_id': 99,
      'attribute_code': 'size'
    }
  ],
  'color_options': [49, 50, 53],
  'size_options': [167, 168, 169, 170, 171],
  'attributes_metadata': rawConfigurableProductAttributesMetadata(),
  'category': [
    {
      'category_id': 15,
      'name': 'Hoodies & Sweatshirts',
      'slug': 'hoodies-and-sweatshirts-15',
      'path': 'men/tops-men/hoodies-and-sweatshirts-men/hoodies-and-sweatshirts-15'
    },
    {
      'category_id': 36,
      'name': 'Eco Friendly',
      'slug': 'eco-friendly-36',
      'path': 'collections/eco-friendly/eco-friendly-36'
    },
    {
      'category_id': 2,
      'name': 'All',
      'slug': 'all-2',
      'path': 'all-2'
    }
  ],
  'url_path': 'men/tops-men/hoodies-and-sweatshirts-men/hoodies-and-sweatshirts-15/bruno-compete-hoodie-99.html'
})
