export const ALLOWED_LICENSES = [
  'Artistic-2.0',
  'Apache-2.0',
  // https://github.com/gtanner/qrcode-terminal/pull/45#issuecomment-1661985667
  // Invalid non-SPDX identifier used by qrcode-terminal
  'Apache 2.0',
  'BSD-2-Clause',
  'BSD-3-Clause',
  'BSD*',
  'Boost',
  'BlueOak-1.0.0',
  'CC-BY-3.0',
  'CC0-1.0',
  'CNRI',
  'Custom: http://www.commonjs.org/',
  'Custom: https://docs.vuestorefront.io/',
  'Custom: https://nuxtjs.org',
  // Used by @vsf-enterprise/paypal-commercetools in its dependency @paypal/checkout-server-sdk@1.0.3
  // If you download the package to your filesystem, you'll see that it's the Apache 2.0 license in fact
  'Custom: https://github.com/paypal/Checkout-NodeJS-SDK/blob/master/LICENSE',
  'Custom: VSFEL',
  'CC-BY-4.0',
  'ISC',
  'MIT',
  'Miros',
  'MPL-2.0',
  'Multics',
  'Naumen',
  'NTP',
  'UNKNOWN',
  'Unicode',
  'Unlicense',
  'UNLICENSED',
  'Universal',
  'Lucent',
  'LGPL-3.0',
  'Open',
  '0BSD',
  'OBSD',
  'PostgreSQ',
  'Public Domain',
  'Python-2.0',
  'Zope',
  'WTFPL',
];
