export const SN_GIFT_CARD = 'gift-card';
export const REMOVE_APPLIED_GIFT_CARD = SN_GIFT_CARD + '/REMOVE_APPLIED_GIFT_CARD';
export const SET_APPLIED_GIFT_CARD = SN_GIFT_CARD + '/SET_APPLIED_GIFT_CARD';
export const UPDATE_GIFT_CARD_TEMPLATE = SN_GIFT_CARD + '/UPDATE_GIFT_CARD_TEMPLATE';
