export const UPDATE_CART_ITEM_DISCOUNT_PRICE_DATA_EVENT_ID = 'UpdateCartItemDiscountPriceEvent';
export const UPDATE_PRODUCT_DEFAULT_DISCOUNT_PRICE_DATA_EVENT_ID = 'UpdateProductDefaultDiscountPriceEvent';
