export const SN_ICMAA_PRODUCT_ALERT = 'ICMAA_PRODUCT_ALERT'
export const ICMAA_PRODUCT_ALERT_SET_PRODUCTS = `${SN_ICMAA_PRODUCT_ALERT}/SET_PRODUCTS`
export const ICMAA_PRODUCT_ALERT_ADD_PRODUCT = `${SN_ICMAA_PRODUCT_ALERT}/ADD_PRODUCT`
export const ICMAA_PRODUCT_ALERT_RMV_PRODUCT = `${SN_ICMAA_PRODUCT_ALERT}/RMV_PRODUCT`
export const ICMAA_PRODUCT_ALERT_CLR_PRODUCT = `${SN_ICMAA_PRODUCT_ALERT}/CLR_PRODUCT`
