export const SN_ICMAA_PRODUCT_ALERT = 'ICMAA_PRODUCT_ALERT'
export const ICMAA_PRODUCT_ALERT_SET_STOCK = `${SN_ICMAA_PRODUCT_ALERT}/SET_STOCK`
export const ICMAA_PRODUCT_ALERT_ADD_STOCK = `${SN_ICMAA_PRODUCT_ALERT}/ADD_STOCK`
export const ICMAA_PRODUCT_ALERT_RMV_STOCK = `${SN_ICMAA_PRODUCT_ALERT}/RMV_STOCK`
export const ICMAA_PRODUCT_ALERT_CLR_STOCK = `${SN_ICMAA_PRODUCT_ALERT}/CLR_STOCK`
export const ICMAA_PRODUCT_ALERT_SET_PRODUCTS_DATA = `${SN_ICMAA_PRODUCT_ALERT}/SET_PRODUCTS_DATA`
export const ICMAA_PRODUCT_ALERT_RMV_PRODUCTS_DATA = `${SN_ICMAA_PRODUCT_ALERT}/RMV_PRODUCTS_DATA`
