
export const SN_CART = 'cart'
export const CART_ADD_ITEM = SN_CART + '/ADD'
export const CART_DEL_ITEM = SN_CART + '/DEL'
export const CART_UPD_ITEM = SN_CART + '/UPD'
export const CART_LOAD_CART = SN_CART + '/LOAD'

export const SN_CATALOG = 'catalog'
export const CATALOG_UPD_CATEGORIES = SN_CATALOG + '/CATALOG_UPD_CATEGORIES'
export const CATALOG_UPD_PRODUCTS = SN_CATALOG + '/UPD_PRODUCTS'
export const CATALOG_UPD_SEARCH_QUERY = SN_CATALOG + '/UPD_SEARCH_QUERY'

export const SN_CHECKOUT = 'checkout'
export const CHECKOUT_PLACE_ORDER = SN_CHECKOUT + '/PLACE_ORDER'
export const CHECKOUT_PROCESS_QUEUE = SN_CHECKOUT + '/PROCESS_QUEUE'
export const CHECKOUT_LOAD_QUEUE = SN_CHECKOUT + '/LOAD_QUEUE'
