import { SN_ICMAA_CMS } from '../abstract/mutation-types'

export const ICMAA_CMS_CATEGORY_EXRTAS_ADD = `${SN_ICMAA_CMS}/ADD_CMS_CATEGORY_EXRTAS`
export const ICMAA_CMS_CATEGORY_EXRTAS_UPD = `${SN_ICMAA_CMS}/UPDATE_CMS_CATEGORY_EXRTAS`
export const ICMAA_CMS_CATEGORY_EXRTAS_RMV = `${SN_ICMAA_CMS}/REMOVE_CMS_CATEGORY_EXRTAS`
