export const ICMAA_CMS_CATEGORY_EXRTAS_ADD = 'ADD_CMS_CATEGORY_EXRTAS'
export const ICMAA_CMS_CATEGORY_EXRTAS_UPD = 'UPDATE_CMS_CATEGORY_EXRTAS'
export const ICMAA_CMS_CATEGORY_EXRTAS_RMV = 'REMOVE_CMS_CATEGORY_EXRTAS'
