export const IS_SHIPPING_METHODS_SYNCING = 'IS_SHIPPING_METHODS_SYNCING';
export const IS_TOTALS_SYNCING = 'IS_TOTALS_SYNCING';
export const IS_PAYMENT_METHODS_SYNCING = 'IS_PAYMENT_METHODS_SYNCING';
export const IS_COUPON_PROCESSING = 'IS_COUPON_PROCESSING';
