import { SN_ICMAA_CMS } from 'icmaa-cms/store/abstract/mutation-types'

export const ICMAA_CATEGORY_EXRTAS_ADD = `${SN_ICMAA_CMS}/ADD_CATEGORY_EXRTAS`
export const ICMAA_CATEGORY_EXRTAS_UPD = `${SN_ICMAA_CMS}/UPDATE_CATEGORY_EXRTAS`
export const ICMAA_CATEGORY_EXRTAS_RMV = `${SN_ICMAA_CMS}/REMOVE_CATEGORY_EXRTAS`
export const ICMAA_CATEGORY_EXRTAS_DEPARTMENT_CHILDCATEGORIES_ADD = `${SN_ICMAA_CMS}/ADD_CATEGORY_EXRTAS_DEPARTMENT_CHILDCATEGORIES`
