import { SN_ICMAA_CMS } from 'icmaa-cms/store/abstract/mutation-types'

export const ICMAA_CATEGORY_EXTRAS_ADD = `${SN_ICMAA_CMS}/ADD_CATEGORY_EXTRAS`
export const ICMAA_CATEGORY_EXTRAS_UPD = `${SN_ICMAA_CMS}/UPDATE_CATEGORY_EXTRAS`
export const ICMAA_CATEGORY_EXTRAS_RMV = `${SN_ICMAA_CMS}/REMOVE_CATEGORY_EXTRAS`
export const ICMAA_CATEGORY_EXTRAS_CHILDCATEGORIES_ADD = `${SN_ICMAA_CMS}/ADD_CATEGORY_EXTRAS_CHILDCATEGORIES`
export const ICMAA_CATEGORY_EXTRAS_DEPARTMENTLOGOS_ADD = `${SN_ICMAA_CMS}/ADD_CATEGORY_EXTRAS_DEPARTMENTLOGOS`
