import { SN_ICMAA_CMS } from 'icmaa-cms/store/abstract/mutation-types'

export const ICMAA_CATEGORY_EXTRAS_CHILDCATEGORIES_ADD = `${SN_ICMAA_CMS}/ADD_CATEGORY_EXTRAS_CHILDCATEGORIES`
export const ICMAA_CATEGORY_EXTRAS_CONTENT_HEADER_ADD = `${SN_ICMAA_CMS}/ADD_CONTENT_HEADER`
export const ICMAA_CATEGORY_EXTRAS_CONTENT_HEADER_RMV = `${SN_ICMAA_CMS}/RMV_CONTENT_HEADER`
