name: "🐛 Bug report"
description: |
  Create a report to help us improve
labels:
  - bug
  - triage-needed
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report, please make sure to [search for existing issues](https://github.com/vuestorefront/vue-storefront/issues) before filing a new one!
  - type: textarea
    attributes:
      label: Describe the Bug
      description: Can you provide a clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    id: currentbehavior
    attributes:
      label: Current behavior
      placeholder: Describe the current behavior pointing exactly why it's not working as intended
  - type: textarea
    id: expectedbehavior
    attributes:
      label: Expected behavior
      placeholder: Describe what the desired behavior should be
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: Please provide the steps to reproduce and if possible a minimal reproducible example of the problem
  - type: input
    attributes:
      label: What version of Vue Storefront are you using?
      description: 'For example: 2.3.4'
    validations:
      required: true
  - type: input
    attributes:
      label: What version of Node.js are you using?
      description: 'For example: 12.0.0'
    validations:
      required: true
  - type: input
    attributes:
      label: What browser (and version) are you using?
      description: 'For example: Chrome, Safari'
    validations:
      required: true
  - type: input
    attributes:
      label: What operating system (and version) are you using?
      description: 'For example: macOS, Windows'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: fixthebug
    attributes:
      label: Able to fix / change the documentation?
      description: Can you handle this change and create a Pull Request?
      options:
        - label: 'Yes'
          required: false
        - label: 'No'
          required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/vuestorefront/vue-storefront/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
