name: "📚 Documentation Issue"
description: |
  Report issues in our documentation
labels:
  - documentation
  - triage-needed
body:
  - type: textarea
    attributes:
      label: Provide a description of requested docs changes
      placeholder: Briefly describe which document needs to be corrected.
    validations:
      required: true
  - type: checkboxes
    id: fixthebug
    attributes:
      label: Able to fix / change the documentation?
      description: Can you handle this change and create a Pull Request?
      options:
        - label: 'Yes'
          required: false
        - label: 'No'
          required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/vuestorefront/vue-storefront/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
