name: "🚀 Feature Request"
description: Sugest a new feature request or improvement on the project
title: '[Feature]: '
labels:
  - feature
  - enhancement
  - triage-needed

body:
  - type: markdown
    attributes:
      value: |
        Please, provide as many information, and knowledge so the feature can be correctly designed and developed.
  - type: textarea
    id: suggestion
    attributes:
      label: How the project can be improved?
      description: What is the motivation for adding / enhancing this feature? Can you describe a concrete use case for this feature or why one of current ones should be enhanced.
      placeholder: Describe the motivation or the concrete use case
    validations:
      required: true
  - type: textarea
    id: acceptcriterea
    attributes:
      label: What are the acceptance criteria?
      description: List the acceptance criteria for this task in a form of a list.
      value: '- [ ]'
  - type: textarea
    id: additionalinfo
    attributes:
      label: Additional information
      description: If you think that any additional information would be useful please provide them here.
  - type: input
    attributes:
      label: What version of Vue Storefront this feature can be implemented?
      description: 'For example: 2.3.4'
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/vuestorefront/vue-storefront/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
