export const SN_BUDSIES = 'budsies';
export const STORE_RATING_SET = SN_BUDSIES + '/STORE_RATING_SET';
export const METRIC_SET = '/METRIC_SET'
export const SET_RUSH_ADDONS_LOADING_PROMISE = SN_BUDSIES + '/SET_RUSH_ADDONS_LOADING_PROMISE';
export const SET_IS_RUSH_ADDONS_LOADED = SN_BUDSIES + '/SET_IS_RUSH_ADDONS_LOADED';
