export const CMS_PRISMIC = 'cmsPrismic'
export const CMS_PRISMIC_ADD_CONTENT_BY_ID = CMS_PRISMIC + '/ADD_CONTENT_BY_ID'
export const CMS_PRISMIC_ADD_CONTENT_BY_TYPE = CMS_PRISMIC + '/ADD_CONTENT_BY_TYPE'
