export const PERSISTED_CUSTOMER_EMAIL = 'PERSISTED_CUSTOMER_EMAIL';
export const PERSISTED_CUSTOMER_FIRST_NAME = 'PERSISTED_CUSTOMER_FIRST_NAME';
export const PERSISTED_CUSTOMER_LAST_NAME = 'PERSISTED_CUSTOMER_LAST_NAME';
export const PERSISTED_CUSTOMER_PHONE_NUMBER = 'PERSISTED_CUSTOMER_PHONE_NUMBER';
export const PERSISTED_CUSTOMER_SHIPPING_COUNTRY = 'PERSISTED_CUSTOMER_SHIPPING_COUNTRY';
export const PERSISTED_CUSTOMER_BILLING_ADDRESS = 'PERSISTED_CUSTOMER_BILLING_ADDRESS';
export const PERSISTED_CUSTOMER_DATA = 'PERSISTED_CUSTOMER_DATA';
export const CUSTOMER_DATA_HASH = 'CUSTOMER_DATA_HASH';
