export const SET_PERSISTED_CUSTOMER_EMAIL = 'SET_PERSISTED_CUSTOMER_EMAIL';
export const SET_PERSISTED_CUSTOMER_FIRST_NAME = 'SET_PERSISTED_CUSTOMER_FIRST_NAME';
export const SET_PERSISTED_CUSTOMER_LAST_NAME = 'SET_PERSISTED_CUSTOMER_LAST_NAME';
export const SET_PERSISTED_CUSTOMER_PHONE_NUMBER = 'SET_PERSISTED_CUSTOMER_PHONE_NUMBER';
export const SET_PERSISTED_CUSTOMER_SHIPPING_COUNTRY = 'SET_PERSISTED_CUSTOMER_SHIPPING_COUNTRY';
export const SET_PERSISTED_CUSTOMER_BILLING_ADDRESS = 'SET_PERSISTED_CUSTOMER_BILLING_ADDRESS';
