export const SET_LAST_USED_CUSTOMER_EMAIL = 'SET_LAST_USED_CUSTOMER_EMAIL';
export const SET_LAST_USED_CUSTOMER_FIRST_NAME = 'SET_LAST_USED_CUSTOMER_FIRST_NAME';
export const SET_LAST_USED_CUSTOMER_LAST_NAME = 'SET_LAST_USED_CUSTOMER_LAST_NAME';
export const SET_LAST_USED_CUSTOMER_PHONE_NUMBER = 'SET_LAST_USED_CUSTOMER_PHONE_NUMBER';
export const SET_LAST_USED_CUSTOMER_SHIPPING_COUNTRY = 'SET_LAST_USED_CUSTOMER_SHIPPING_COUNTRY';
export const SET_LAST_USED_CUSTOMER_BILLING_ADDRESS = 'SET_LAST_USED_CUSTOMER_BILLING_ADDRESS';
