export const SN_ICMAA_CATEGORY = 'ICMAA_CATEGORY'
export const ICMAA_CATEGORY_LIST_ADD_CATEGORY_LIST = `${SN_ICMAA_CATEGORY}/ADD_CATEGORY_LIST`
export const ICMAA_CATEGORY_LIST_ADD_PRODUCT = `${SN_ICMAA_CATEGORY}/ADD_PRODUCT`
