export default interface CartState {
  isMicrocartOpen: boolean,
  itemsAfterPlatformTotals: any,
  platformTotals: any,
  platformTotalSegments: any,
  cartIsLoaded: boolean,
  cartServerToken: string,
  shipping: any,
  payment: any,
  cartItemsHash: string,
  cartServerLastSyncDate: number,
  cartServerLastTotalsSyncDate: number,
  cartItems: any[],
  connectBypassCount: number,
  isAddingToCart: boolean,
  isLocalDataLoaded: boolean,
  productDiscountedPrice: Record<string, number>,
  isShippingMethodsSyncing: boolean,
  isTotalsSyncing: boolean,
  isPaymentMethodsSyncing: boolean,
  isCouponProcessing: boolean
}
