query ReviewList (
    $filter: ReviewFilterInput,
    $pageSize: Int,
    $currentPage: Int
  ) {
  reviews(
    filter: $filter
    pageSize: $pageSize
    currentPage: $currentPage
  )
  {
    hits
    suggest
  }
}