export default interface Product {
  category: Array<Object>
  category_ids: Array<string>
  climate: string
  color: string
  color_options: Array<number>
  configurable_children: Array<Object>
  configurable_options: Array<Object>
  custom_attributes: any
  description: string
  eco_collection: string
  erin_recommends: string
  errors: Object
  final_price: number
  gift_message_available: string
  has_options: string
  id: number
  image: string
  info: Object
  is_configured: true
  material: string
  max_price: number
  max_regular_price: number
  media_gallery: Array<Object>
  minimal_price: number
  minimal_regular_price: number
  msrp_display_actual_price_type: string
  name: string
  new: string
  options: Array<Object>
  parentSku: string
  pattern: string
  performance_fabric: string
  price: number
  priceInclTax: number
  priceTax: number
  product_links: Array<Object>
  product_option: Object
  regular_price: number
  required_options: string
  sale: string
  sgn: string
  size: string
  size_options: Array<number>
  sku: string
  slug: string
  small_image: string
  specialPriceInclTax: any
  specialPriceTax: any
  special_price: number
  status: number
  stock: Object
  style_general: string
  tax_class_id: string
  thumbnail: string
  tsk: number
  type_id: string
  url_key: string
  visibility: number
  _score: number
  qty: number
}
