export const FETCH_ORDERS_HISTORY = 'FETCH_ORDERS_HISTORY';
export const FETCH_SUGGESTED_PRODUCTS = 'FETCH_SUGGESTED_PRODUCTS';
export const REORDER_ITEM = 'REORDER_ITEM';
export const FETCH_ORDER_DETAILS = 'FETCH_ORDER_DETAILS';
export const SUBMIT_TAX_ID_UPDATE_REQUEST = 'SUBMIT_TAX_ID_UPDATE_REQUEST';
export const SUBMIT_ORDER_ADDRESS_UPDATE_REQUEST = 'SUBMIT_ORDER_ADDRESS_UPDATE_REQUEST';
