export const SN_BACKEND_SETTINGS = 'backend-settings';
export const SET_BACKEND_SETTINGS = SN_BACKEND_SETTINGS + 'SET_BACKEND_SETTINGS';
export const SET_IS_SYNCED = SN_BACKEND_SETTINGS + 'SET_IS_SYNCED';
