import { Request } from 'express';
import fetch from 'isomorphic-fetch';

import { serverHooksExecutors } from '@vue-storefront/core/server/hooks'
import { extractCookieValue } from '../helpers/extract-cookie-value.function'
import { cacheInstanceFactory } from './utils/cache-instance';

const gracefulShutdown = require('http-graceful-shutdown')
const qs = require('qs')
const config = require('config')
const path = require('path')
const glob = require('glob')
const fs = require('fs')
const rootPath = require('app-root-path').path
const resolve = file => path.resolve(rootPath, file)
const serverExtensions = glob.sync('src/modules/*/server.{ts,js}')
const configProviders: Function[] = []

const PM2_INSTANCE_ID = process.env.NODE_APP_INSTANCE || process.env.pm_id || process.env.PM2_INSTANCE_ID;
const PM2_PROCESS_NAME = process.env.name || process.env.PM2_PROCESS_NAME;

function getProcessLogPrefix () {
  const parts: string[] = [`pid:${process.pid}`];

  if (PM2_INSTANCE_ID !== undefined && PM2_INSTANCE_ID !== null && `${PM2_INSTANCE_ID}`.length > 0) {
    parts.push(`pm2:${PM2_INSTANCE_ID}`);
  }

  if (PM2_PROCESS_NAME) {
    parts.push(`name:${PM2_PROCESS_NAME}`);
  }

  return `[${parts.join(' ')}]`;
}

serverExtensions.map(serverModule => {
  const module = require(resolve(serverModule))
  if (module.configProvider && typeof module.configProvider === 'function') {
    configProviders.push(module.configProvider)
  }
})

serverHooksExecutors.afterProcessStarted(config.server)
const express = require('express')
const ms = require('ms')
const helmet = require('helmet')

const cache = cacheInstanceFactory();
const apiStatus = require('./utils/api-status')
const HTMLContent = require('../pages/Compilation')
const ssr = require('./utils/ssr-renderer')

const compileOptions = {
  escape: /{{([^{][\s\S]+?[^}])}}/g,
  interpolate: /{{{([\s\S]+?)}}}/g
}
const NOT_ALLOWED_SSR_EXTENSIONS_REGEX = new RegExp(`^.*\\.(${config.server.ssrDisabledFor.extensions.join('|')})$`)

const isProd = process.env.NODE_ENV === 'production'

const app = express()

serverHooksExecutors.afterApplicationInitialized({ app, config: config.server, isProd })

const templatesCache = ssr.initTemplatesCache(config, compileOptions)

let renderer

if (isProd) {
  // In production: create server renderer using server bundle and index HTML
  // template from real fs.
  // The server bundle is generated by vue-ssr-webpack-plugin.
  const clientManifest = require(resolve('dist/client/vue-ssr-client-manifest.json'))
  const bundle = require(resolve('dist/server/vue-ssr-bundle.json'))
  // src/index.template.html is processed by html-webpack-plugin to inject
  // build assets and output as dist/client/index.html.
  // TODO: Add dynamic templates loading from (config based?) list
  renderer = ssr.createRenderer(bundle, clientManifest)
} else {
  // In development: setup the dev server with watch and hot-reload,
  // and create a new renderer on bundle / index template update.
  require(resolve('core/build/dev-server'))(app, (bundle, template) => {
    templatesCache['default'] = ssr.compileTemplate(template, compileOptions) // Important Notice: template switching doesn't work with dev server because of the HMR
    renderer = ssr.createRenderer(bundle)
  })
}

function healthCheck (req, res) {
  res.status(200).end();
}

function forwardCacheInvalidation (url: string): void {
  fetch(url)
    .then(response => response.text())
    .then(body => {
      if (!body) return

      try {
        if (JSON.parse(body).code !== 200) console.log(body)
      } catch (error) {
        console.error('Invalid Cache Invalidation response format', error)
      }
    })
    .catch(error => console.error(error))
}

function invalidateCache (req, res) {
  if (config.server.useOutputCache && cache) {
    if (req.query.tag && req.query.key) { // clear cache pages for specific query tag
      if (req.query.key !== config.server.invalidateCacheKey) {
        console.error('Invalid cache invalidation key')
        apiStatus(res, 'Invalid cache invalidation key', 500)
        return
      }
      console.log(`Clear cache request for [${req.query.tag}]`)
      let tags = []
      if (req.query.tag === '*') {
        tags = config.server.availableCacheTags
      } else {
        tags = req.query.tag.split(',')
      }
      const subPromises = []

      serverHooksExecutors.beforeCacheInvalidated({ tags, req })

      tags.forEach(tag => {
        if (config.server.availableCacheTags.indexOf(tag) >= 0 || config.server.availableCacheTags.find(t => {
          return tag.indexOf(t) === 0
        })) {
          subPromises.push(cache.invalidate(tag).then(() => {
            console.log(`Tags invalidated successfully for [${tag}]`)
          }))
        } else {
          console.error(`Invalid tag name ${tag}`)
        }
      })

      Promise.all(subPromises).then(r => {
        apiStatus(res, `Tags invalidated successfully [${req.query.tag}]`, 200)
      }).catch(error => {
        apiStatus(res, error, 500)
        console.error(error)
      }).finally(() => {
        serverHooksExecutors.afterCacheInvalidated({ tags, req })
      })

      if (config.server.invalidateCacheForwarding) { // forward invalidate request to the next server in the chain
        if (!req.query.forwardedFrom && config.server.invalidateCacheForwardUrl) { // don't forward forwarded requests
          forwardCacheInvalidation(config.server.invalidateCacheForwardUrl + req.query.tag + '&forwardedFrom=vs')
        }
      }
    } else {
      apiStatus(res, 'Invalid parameters for Clear cache request', 500)
      console.error('Invalid parameters for Clear cache request')
    }
  } else {
    apiStatus(res, 'Cache invalidation is not required, output cache is disabled', 200)
  }
}

const serve = (path, cache, options?) => express.static(resolve(path), Object.assign({
  fallthrough: false,
  setHeaders: cache && isProd ? function (res, path) {
    const mimeType = express.static.mime.lookup(path);
    let maxAge = config.expireHeaders.default;
    if (config.expireHeaders.hasOwnProperty(mimeType)) {
      maxAge = config.expireHeaders.get(mimeType);
    }
    res.setHeader('Cache-Control', 'public, max-age=' + ms(maxAge) / 1000);
  } : null
}, options))

const themeRoot = require('../build/theme-path')
const TEST_GROUP_ID_COOKIE_KEY = config.abTesting?.cookieKey;

if (config.server.helmet && config.server.helmet.enabled && isProd) {
  app.use(helmet(config.server.helmet.config))
}

app.use('/dist', serve('dist/client', true))
app.use('/assets', serve(themeRoot + '/assets', true))
app.use('/service-worker.js', serve('dist/client/service-worker.js', false, {
  setHeaders: function (res, path, stat) {
    res.set('Content-Type', 'text/javascript; charset=UTF-8')
  }
}))

app.post('/invalidate', invalidateCache)
app.get('/invalidate', invalidateCache)
app.get('/healthcheck', healthCheck)

function cacheVersion (req, res) {
  res.send(fs.readFileSync(resolve('core/build/cache-version.json')))
}

const ignoredQueryKeys = [
  'srsltid',
  'utm_source',
  'utm_medium',
  'utm_campaign',
  '_kx',
  'fbclid',
  'utm_term',
  'utm_content',
  'utm_id',
  'gad_source',
  'gclid',
  'id',
  'gbraid',
  'dclid',
  'campaign',
  'data',
  'content',
  'msclkid',
  'uri',
  'url',
  'dest',
  'redirect',
  'file',
  'target',
  'mc_cid',
  'mc_eid',
  'sscid',
  'gad_campaignid',
  'gQT',
  'wbraid',
  'ttclid',
  'li_fat_id',
  'twclid',
  'sccid',
  'rdt_cid',
  'irclickid',
  'awc',
  'pp',
  'audience',
  'ref',
  'continueFlag',
  'hc_location',
  'qty',
  'email',
  'epik',
  'user',
  'SID',
  'referral_code',
  'newsletter-subscription-form-email-input',
  'redirect-target',
  'image-url',
  'order_item_id'
];

function generateCacheKey (site: string, req: Request) {
  const url = new URL(`${req.protocol}://${req.get('host')}${req.originalUrl}`);

  ignoredQueryKeys.forEach((key) => url.searchParams.delete(key));

  return `page:${site}:${url.pathname}${url.search}`;
}

app.get('/cache-version.json', cacheVersion)

let globalContextConfig: any = null;

app.get('*', async (req, res, next) => {
  if (NOT_ALLOWED_SSR_EXTENSIONS_REGEX.test(req.path)) {
    apiStatus(res, 'Vue Storefront: Resource is not found', 404)
    return
  }

  const s = Date.now()
  const errorHandler = err => {
    if (err && err.code === 404) {
      if (NOT_ALLOWED_SSR_EXTENSIONS_REGEX.test(req.path)) {
        console.error(`Resource is not found : ${req.url}`)
        return apiStatus(res, 'Vue Storefront: Resource is not found', 404)
      } else {
        console.error(`Redirect for resource not found : ${req.url}`)
        return res.redirect('/page-not-found')
      }
    } else {
      console.error(`Error during render : ${req.url}`)
      console.error(err)
      serverHooksExecutors.ssrException({ err, req, isProd })
      return res.redirect('/error')
    }
  }

  if (!req.path.endsWith('/')) {
    const hasQuery = Object.values(req.query).length;
    let redirectUrl = `${req.path}/`;

    if (hasQuery) {
      redirectUrl += '?' + qs.stringify(req.query);
    }

    return res.redirect(301, redirectUrl);
  }

  const site = req.headers['x-vs-store-code'] || 'main'
  let cacheKey = generateCacheKey(site, req);

  if (TEST_GROUP_ID_COOKIE_KEY) {
    const testGroupId = extractCookieValue(TEST_GROUP_ID_COOKIE_KEY, req?.headers?.cookie);

    if (testGroupId) {
      cacheKey += `:${testGroupId}`;
    }
  }

  const dynamicRequestHandler = (renderer, config) => {
    if (!renderer) {
      res.setHeader('Content-Type', 'text/html')
      res.status(202).end(HTMLContent)
      return next()
    }
    const context = ssr.initSSRRequestContext(app, req, res, config)
    renderer.renderToString(context).then(output => {
      if (!res.get('content-type')) {
        res.setHeader('Content-Type', 'text/html')
      }
      let tagsArray = []
      if (config.server.useOutputCacheTagging && context.output.cacheTags && context.output.cacheTags.size > 0) {
        tagsArray = Array.from(context.output.cacheTags)
        const cacheTags = tagsArray.join(' ')
        res.setHeader('X-VS-Cache-Tags', cacheTags)
        console.log(`cache tags for the request: ${cacheTags}`)
      }

      const beforeOutputRenderedResponse = serverHooksExecutors.beforeOutputRenderedResponse({
        req,
        res,
        context,
        output,
        isProd
      })

      if (typeof beforeOutputRenderedResponse.output === 'string') {
        output = beforeOutputRenderedResponse.output
      } else if (typeof beforeOutputRenderedResponse === 'string') {
        output = beforeOutputRenderedResponse
      }

      output = ssr.applyAdvancedOutputProcessing(context, output, templatesCache, isProd);
      if (config.server.useOutputCache && cache && !context.output.cacheTags.has('no-cache')) {
        cache.set(
          cacheKey,
          {
            headers: res.getHeaders(),
            body: output,
            httpCode: res.statusCode,
            redirect: context.output.redirect
          },
          tagsArray
        ).catch(errorHandler)
      }

      const afterOutputRenderedResponse = serverHooksExecutors.afterOutputRenderedResponse({
        req,
        res,
        context,
        output,
        isProd
      })

      if (context.output.redirect) {
        return res.redirect(
          context.output.redirect.code,
          context.output.redirect.path
        );
      }

      if (typeof afterOutputRenderedResponse === 'string') {
        res.end(afterOutputRenderedResponse)
      } else if (typeof afterOutputRenderedResponse.output === 'string') {
        res.end(afterOutputRenderedResponse.output)
      } else {
        res.end(output)
      }

      console.log(`${getProcessLogPrefix()} whole request [${req.url}]: ${Date.now() - s}ms`)
      next()
    }).catch(errorHandler)
      .finally(() => {
        ssr.clearContext(context)
      })
  }

  const dynamicCacheHandler = (config) => {
    if (config.server.useOutputCache && cache) {
      cache.get(
        cacheKey
      ).then(output => {
        if (output !== null) {
          if (output.headers) {
            for (const header of Object.keys(output.headers)) {
              res.setHeader(header, output.headers[header])
            }
          }
          res.setHeader('X-VS-Cache', 'Hit')

          if (output.httpCode) {
            res.status(output.httpCode)
          }

          if (output.redirect) {
            res.redirect(output.redirect.code, output.redirect.path)
            console.log(`${getProcessLogPrefix()} redirect cache hit [${req.url}], cached request: ${Date.now() - s}ms`)
            return
          }

          if (output.body) {
            res.end(output.body)
          } else {
            res.setHeader('Content-Type', 'text/html')
            res.end(output)
          }
          console.log(`${getProcessLogPrefix()} cache hit [${req.url}], cached request: ${Date.now() - s}ms`)
          next()
        } else {
          res.setHeader('X-VS-Cache', 'Miss')
          console.log(`${getProcessLogPrefix()} cache miss [${req.url}], request: ${Date.now() - s}ms`)
          dynamicRequestHandler(renderer, config) // render response
        }
      }).catch(errorHandler)
    } else {
      dynamicRequestHandler(renderer, config)
    }
  }

  let requestContextConfig: any = config.util.extendDeep({}, config);

  if (config.server.dynamicConfigReload && !globalContextConfig) {
    if (configProviders.length > 0) {
      const configPromises = [];
      configProviders.forEach(configProvider => {
        if (typeof configProvider === 'function') {
          configPromises.push(configProvider(req).then(loadedConfig => {
            requestContextConfig = config.util.extendDeep(requestContextConfig, loadedConfig)
          }).catch(() => {
            if (!config.server.dynamicConfigContinueOnError) {
              if (req.url !== '/error') {
                res.redirect('/error')
              }
            }
          }))
        }
      })
      await Promise.all(configPromises)

      if (!config.server.dynamicConfigReloadWithEachRequest) {
        globalContextConfig = config.util.extendDeep({}, requestContextConfig)
      }
    }
  } else if (globalContextConfig) {
    requestContextConfig = config.util.extendDeep({}, globalContextConfig)
  }

  dynamicCacheHandler(requestContextConfig)
})

let port = process.env.PORT || config.server.port
const host = process.env.HOST || config.server.host
let keepAliveTimeout = process.env.KEEP_ALIVE_TIMEOUT || config.server.keepAliveTimeout
keepAliveTimeout = parseInt(keepAliveTimeout) || 5000
const start = () => {
  const server = app.listen(port, host);
  server.keepAliveTimeout = keepAliveTimeout;
  server.headersTimeout = keepAliveTimeout + 1000;
  gracefulShutdown(server);

  server.on('listening', () => {
    console.log(`\n\n----------------------------------------------------------`)
    console.log('|                                                        |')
    console.log(`| Vue Storefront Server started at http://${host}:${port} |`)
    console.log(`| Worker ${getProcessLogPrefix()}                                         |`)
    console.log('|                                                        |')
    console.log(`----------------------------------------------------------\n\n`)

    serverHooksExecutors.httpServerIsReady({ server, config: config.server, isProd })

    if (process && typeof process.send === 'function') {
      process.send('ready');
    }
  }).on('error', (e: any) => {
    if (e.code === 'EADDRINUSE') {
      port = parseInt(port) + 1
      console.log(`The port is already in use, trying ${port}`)
      start()
    }
  })
}
start()
