query customAttributeMetadata ($attributes: AttributeInput!, $_sourceInclude: [String]) {
  customAttributeMetadata(
    attributes: $attributes
    _sourceInclude: $_sourceInclude
  )
  {
    hits
  }
}