query customAttributeMetadata ($attributes: AttributeInput!, $_sourceIncludes: [String]) {
  customAttributeMetadata(
    attributes: $attributes
    _sourceIncludes: $_sourceIncludes
  )
  {
    hits
  }
}