query ProductListFilters (
    $filter: ProductFilterInput,
    $search: String!,
    $pageSize: Int,
    $currentPage: Int,
    $sort: ProductSortInput,
    $_sourceInclude: [String],
    $_sourceExclude: [String]
  ) {
    products(
      filter: $filter
      search: $search
      pageSize: $pageSize
      currentPage: $currentPage
      sort: $sort
      _sourceInclude: $_sourceInclude
      _sourceExclude: $_sourceExclude
    )
    {
      items
      total_count
      aggregations
      sort_fields{
        options {
          value
        }
      }
      page_info{
        page_size
        current_page
      }
    }
}