export const SN_ICMAA_COMPETITIONS = 'ICMAA_COMPETITIONS'
export const ICMAA_COMPETITIONS_ADD = `${SN_ICMAA_COMPETITIONS}/ADD`
export const ICMAA_COMPETITIONS_UPD = `${SN_ICMAA_COMPETITIONS}/UPD`
export const ICMAA_COMPETITIONS_RMV = `${SN_ICMAA_COMPETITIONS}/RMV`
