on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  continous-integration:
    name: "Continuous Integration"
    uses: ./.github/workflows/ci-integrations.yml
    secrets: inherit
    with:
      enterprise: false