name: Deploy Docs
on:
  push:
    branches:
      - release/next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - shell: bash
        run: |
          echo "1.0.`date +%s`" > version.txt
      - name: Upload version artifact
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(cat version.txt)
      - name: Build and publish docker image
        # uses: elgohr/Publish-Docker-Github-Action@master
        # 3.04 is hardcoded as a workaround for https://github.com/elgohr/Publish-Docker-Github-Action/issues/134
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: docs-storefrontcloud-io/v2:${{ steps.get_version.outputs.VERSION }}
          registry: registry.storefrontcloud.io
          username: ${{ secrets.DOCS_CLOUD_USERNAME }}
          password: ${{ secrets.DOCS_CLOUD_PASSWORD }}
          workdir: .
          dockerfile: ./packages/core/docs/Dockerfile
          buildoptions: "--compress"