name: Run E2E Tests
on:
  workflow_dispatch:
    inputs:
      tags_include:
        description: "Include tags"
        required: false
      tags_exclude:
        description: "Exclude tags"
        required: false
      package:
        description: "Package"
        required: true
        default: "ct"
      browser:
        description: "Browser"
        required: true
        default: "chrome"
jobs:
  run_e2e_tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build tools
        run: yarn build:${{ github.event.inputs.package }}:tools

      - name: Run cypress tests
        uses: cypress-io/github-action@v2.8.2
        with:
          start: yarn dev:${{ github.event.inputs.package }}
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180
          command: yarn run test:e2e:${{ github.event.inputs.package }}:hl
          browser: ${{ github.event.inputs.browser }}
          headless: true
          install: false
        env:
          CYPRESS_INCLUDE_TAGS: ${{ github.event.inputs.tags_include }}
          CYPRESS_EXCLUDE_TAGS: ${{ github.event.inputs.tags_exclude }}

      - name: Generate report
        if: ${{ always() }}
        run: yarn test:e2e:${{ github.event.inputs.package }}:generate:report

      - name: Upload bp report artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: report-bp
          path: "packages/boilerplate/theme/tests/e2e/report"
          if-no-files-found: ignore

      - name: Upload ct report artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: report-ct
          path: "packages/commercetools/theme/tests/e2e/report"
          if-no-files-found: ignore
