export const SET_FIRST_TOUCH = 'SET_FIRST_TOUCH';
export const SET_LAST_TOUCH = 'SET_LAST_TOUCH';
export const MARK_FIRST_TOUCH_SENT = 'MARK_FIRST_TOUCH_SENT';
export const MARK_LAST_TOUCH_SENT = 'MARK_LAST_TOUCH_SENT';
