export const SET_TRAFFIC_ATTRIBUTION = 'SET_TRAFFIC_ATTRIBUTION';
export const SET_LAST_MEANINGFUL_TRAFFIC_ATTRIBUTION = 'SET_LAST_MEANINGFUL_TRAFFIC_ATTRIBUTION';
export const CLEAR_LAST_MEANINGFUL_TRAFFIC_ATTRIBUTION = 'CLEAR_LAST_MEANINGFUL_TRAFFIC_ATTRIBUTION';
